library:
  source-dirs: src
tests:
  hylo-quick-test:
    source-dirs: test
    main: Tests.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hylo-quick
    - QuickCheck
copyright: 2020 Michael Dürig
dependencies:
- base >= 4.7 && < 5
- recursion-schemes
name: hylo-quick
version: 0.1.0.0
extra-source-files:
- README.md
author: Michael Dürig
github: mduerig/hylo-quick
license: BSD3
executables:
  hylo-quick-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hylo-quick
description: Please see the README on GitHub at <https://github.com/mduerig/hylo-quick>
